    shared.Configs = {
        Enabled = true,
        BreakAutoFarm = false,
        RedeemCode = true,
        Speed = 2,  
        SuperFarming = true,
        GithubUrl = 'https://raw.githubusercontent.com/Chayen2543/pixel/refs/heads/main/summon.lua',
        GithubConfigUrl = 'https://raw.githubusercontent.com/Chayen2543/pixel/refs/heads/main/config.lua',
        JobID = '',
        TradingMode = false,
        FreddyFarm = false,
        Difficulty = 'Hard',
        AutoSkipWave = true,
        CustomTrading = {
            ['Enabled'] = false,
            ['Username'] = {
                'Chaayen001',
                'Chaayen002',
                'Chaayen003',
                'Chaayen004',
                'Chaayen005',
                'Chaayen006',
                'Chaayen007',
                'Chaayen008',
                'rikimaru260',
                'sacralzen603',
                'eldermeow1',
                'eldermeow2',
                'eldermeow3',
                'eldermeow4',
                'eldermeow5',
                'eldermeow6',
                'eldermeow7',
                'eldermeow8',
                'eldermeow19',
                'eldermeow20',
            },
        },
        AutoTrading = {
            ['Enabled'] = false,
            ['Main User'] = 'HugsPrawn070',
            ['JobID'] = 'efc5f6f6-f7a7-4279-bdd3-c7fe79116527',
        },
    };
